// DO NOT EDIT. This file is generated by deco.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $$$$$$$$$0 from "./actions/validatePassword.ts";
import * as $$$$$$0 from "./sections/PasswordCheck.tsx";

const manifest = {
  "sections": {
    "password/sections/PasswordCheck.tsx": $$$$$$0,
  },
  "actions": {
    "password/actions/validatePassword.ts": $$$$$$$$$0,
  },
  "name": "password",
  "baseUrl": import.meta.url,
};

export type Manifest = typeof manifest;

export default manifest;
